### ISSUE TITLE
Problems with completion window appearing below Tiddler 

### ISSUE THREAD

**Issue by ssoriche** [Gk0Wk/CodeMirror-Mode-TiddlyWiki5#3]
This plugin looks really interesting, I like the suggestions for links automatically rather than relying on my pressing ctrl-space to access them, however the completion window appears below the Tiddler I'm editing. I had the same problem with CMPlus and the author mentioned that it was an issue with the z-axis. It appears CodeMirror-Mode-TiddlyWiki5 suffers the same issue.

<img width="923" alt="image" src="https://user-images.githubusercontent.com/19838/131135412-5c45c529-cf9e-4c27-9245-6cb0ce13552f.png">

**Comment by oflg** [comment]
@ssoriche It is caused by 'Sticky titles'. The v0.0.3 has solved it.

**Comment by Gk0Wk** [comment]
Will updating the plug-in to v0.0.3 can help? I modify the z-index in v0.0.3.

**Comment by ssoriche** [comment]
Sorry I should have included it when I opened the issue. I am running v0.0.3 with TiddlyWiki 5.1.23.

I downloaded the latest release and when installing it, it reported I already had v0.0.3 installed.

**Comment by ssoriche** [comment]
Also, I turned off 'Sticky titles', and the suggestion box is still beneath the Tiddler being edited.

**Comment by Gk0Wk** [comment]
It's okay. I think there must be something (plugins, themes, or you yourself) to modify the `z-index` (the layer level) of the toddler. We can do an experiment to determine the most appropriate `z-index` value:

Open up `$:/plugins/Gk0Wk/codemirror-tiddlywiki5/style.css`, change `.CodeMirror-hints{z-index:200!important}` to `.CodeMirror-hints{z-index:300!important}` or something lager, until the suggestion box can be above the editor.

**Comment by ssoriche** [comment]
Thank you. Adjusting the value to 500 appears to have solved it (400 was too little).

**Comment by Gk0Wk** [comment]
Thanks, I will change it larger.
